### ISSUE TITLE
Tutorial screen

### ISSUE THREAD

**Issue by xen-42** [xen-42/mcgill-ugl-2022#53]
- [ ] Describe how stress works
- [ ] Describe the goal (write assignment -> scan -> submit)
- [x] Refactor the current template implementation to use a prefab to be consistent between the pause menu version and the main menu version
- [x] Move the tutorial to when you have joined the lobby (can read while they pick their settings).

**Comment by daphneducharmee** [comment]
- [ ] Change tutorial to a canvas prefab
